_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
hotlink: false
origin: 'https://tpx-sk-acquia-name.prod.acquia-sites.com'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
