_core:
  default_config_hash: QdiqmcH9tjpstXqCQKv4G4rHYE4HjWLFkVzyqooqEWM
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: false
logo:
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: auto
classic_toolbar: horizontal
secondary_toolbar_frontend: false
high_contrast_mode: false
accent_color: ''
focus_color: ''
layout_density: small
show_description_toggle: true
show_user_theme_settings: true
icon_default: true
icon_path: ''
icon_upload: ''
