_core:
  default_config_hash: rpfRQVoEn2ZWd_lw-iULKPiuina5CqcmzXWlz1OjTwM
name: tpx_sk_subsitename
mail: tpx-sk-subsitename-kebab@tpx-sk-subsitsube-domain
simple_address: false
sitestyle: false
textonly: true
linkonly: false
user_plaintext_field: ''
format: full_html
preserve_class: false
advanced:
  incoming: false
  key: WwxviJXCrY09lwnIXDC29RW1Mc-lqnOQ2COseJZUmVQ
